import { google } from 'googleapis'; import { parseGoogleDriveFileId } from '@/lib/drive-url';
export type DriveFile={id:string;name:string;mimeType:string;data:string};
export interface DriveService { getFile(url:string):Promise<DriveFile> } export interface SheetsService { upsert(spreadsheetId:string,record:Record<string,unknown>):Promise<void> } export interface DocsService { generate(input:{templateId:string;folderId?:string;name:string;values:Record<string,string>}):Promise<{id:string;url:string}> }
const mockDrive:DriveService={async getFile(url){return{id:parseGoogleDriveFileId(url),name:'demo-work.pdf',mimeType:'application/pdf',data:Buffer.from('mock').toString('base64')}}};
const mockSheets:SheetsService={async upsert(){}}; const mockDocs:DocsService={async generate(i){const id=`mock-${encodeURIComponent(i.name)}`;return{id,url:`https://docs.google.com/document/d/${id}/edit`}}};
function auth(){return new google.auth.JWT({email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,key:process.env.GOOGLE_PRIVATE_KEY?.replace(/\\n/g,'\n'),scopes:['https://www.googleapis.com/auth/drive.file','https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/documents'],subject:process.env.GOOGLE_IMPERSONATED_USER});}
const realDrive:DriveService={async getFile(url){const id=parseGoogleDriveFileId(url),drive=google.drive({version:'v3',auth:auth()});const meta=await drive.files.get({fileId:id,fields:'id,name,mimeType,size'});const size=Number(meta.data.size??0);if(size>Number(process.env.MAX_DRIVE_FILE_BYTES??20971520))throw new Error('Ֆայլը գերազանցում է թույլատրելի չափը։');if(!['application/pdf','image/png','image/jpeg'].includes(meta.data.mimeType??''))throw new Error('Թույլատրվում են միայն PDF կամ նկար ֆայլեր։');const body=await drive.files.get({fileId:id,alt:'media'},{responseType:'arraybuffer'});return{id,name:meta.data.name??id,mimeType:meta.data.mimeType!,data:Buffer.from(body.data as ArrayBuffer).toString('base64')}}};
export const driveService=process.env.MOCK_EXTERNAL_SERVICES==='true'?mockDrive:realDrive; export const sheetsService=mockSheets; export const docsService=mockDocs;
export function docReplacements(values:Record<string,string>){return Object.entries(values).map(([key,value])=>({replaceAllText:{containsText:{text:`{{${key}}}`,matchCase:true},replaceText:value}}));}
export function upsertRow(rows:unknown[][],record:Record<string,unknown>){const header=rows[0]?.map(String)??Object.keys(record);const values=header.map(k=>record[k]??'');const index=rows.findIndex((r,i)=>i>0&&r[0]===record.record_id);return index<0?[...rows.length?rows:[header],values]:rows.map((r,i)=>i===index?values:r);}
